### ISSUE TITLE
What are typical use cases for VocExcel?

### ISSUE THREAD

**Issue by dalito** [surroundaustralia/VocExcel#22]
We currently use VocExcel to create a first version of a SKOS vocabulary for catalysis research data. Different groups work independently on (Excel) files that are joined at some point. After joining some cleaning is required to remove duplicates and inconsistencies. Next the cleaned vocabulary may be split again to several Excel files for a second iteration / review of the vocabulary by domain experts (with limited SKOS knowledge). This second splitting may be based on different criteria then the first split, for example we start collecting vocabularies by sub-discipline but then do the second iteration after a split by applied methods (methods are shared by several but not all sub-disciplines).

How does your typical use case look like? Do you also use VocExcel for vocabularies that have matured?

**Comment by peterphilips** [comment]
Hey @dalito, sorry for the late response and also thank you for your developments in the code. 

A typical use case by a user would include them bringing up a vocabulary they've established, and mapping out/inputting the various links and details in the spreadsheet. The approach with multiple vocabularies is not so different as it also includes some 'cleanup'. 

I am aware of some use-cases for vocabularies which have matured in the case they may be referred later down the track/archived for future use in a better 'linked' format.

Let me know if you have any other questions.
