### ISSUE TITLE
Provenance info for concepts not exported

### ISSUE THREAD

**Issue by dalito** [surroundaustralia/VocExcel#29]
It was removed (commented out) as part of #4, specifically in commit 5e996f6109c5270621e90398315cdeba96373c8b. @peterphilips Was that intended?

If yes, would you mind an option to report provenance again in rdf/turtle output?

**Comment by peterphilips** [comment]
Hi @dalito , I can definitely implement that again. I initially removed it because it was under-used.

I think I'll create a 0.4.4 with the provenance option

**Comment by dalito** [comment]
I tried to just reactivate the code but it results in failing tests. I did not look in more detail why.

**Comment by peterphilips** [comment]
Ah yes - since it's a fixed template design, the template itself (excel sheet) has to be shifted as well.

**Comment by peterphilips** [comment]
I shouldhave something for you by the end of today

**Comment by peterphilips** [comment]
@dalito I found it was unnecessary to recreate a new template version, I just had to clean up the code.

Good pickup! 

Refer to 0faa491625d66d439c5d4883d468a5c378d483e9 as I reimplemented into all versions of vocexcel
