### ISSUE TITLE
Move VocExcel to match SURROUND Python repo expectations

### ISSUE THREAD

**Issue by nicholascar** [surroundaustralia/VocExcel#6]
Like all other SURROUND python projects.

* implement @recalcitrantsupplant Python setup
    * use Poetry
    * auto-generate requirements.txt using Poetry
    * precommit `black` of all Python files
    * auto import optimising
    * ... (from David's procedures)

**Comment by peterphilips** [comment]
see 106a0341de6d332eb036e4c5ca5c7add970df003
