### ISSUE TITLE
Update vocexcel.surroundaustralia.com for 0.4.0

### ISSUE THREAD

**Issue by nicholascar** [surroundaustralia/VocExcel#9]
* [x] update vocexcel.surroundaustralia.com documentation online
* [x] create some minor documentation for vocexel-ui repo
* [x] update the online library use (using VocExcel 0.4.0) (Jamie)

**Comment by peterphilips** [comment]
See (https://bitbucket.org/surroundbitbucket/vocexcel-ui/src/read_me_main/) for brief vocexcel ui read me, and https://vocexcel.surroundaustralia.com/ to confirm working access
